# Generated by Django 5.1.1 on 2024-10-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unique_id',
            field=models.AutoField(default=1001, primary_key=True, serialize=False),
        ),
    ]
