# Generated by Django 5.1.1 on 2024-10-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_userprofile_id_userprofile_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unique_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
