# Generated by Django 5.1.1 on 2024-10-21 14:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userprofile_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
